version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip3 install flask

  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin <ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com
  
  build:
    commands:
      - docker build -t wsi-ecr .
      - docker tag wsi-ecr:latest <ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/wsi-ecr:latest
    
        
  post_build:
    commands:
      - docker push <ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/wsi-ecr:latest
artifacts:
  files:
    - appspec.yml
    - src/app.py
    - start.sh
    - install.sh
    - stop.sh